language: objective-c
osx_image: xcode8
rvm:
  - 2.2.2

env:
  global:
    - WORKSPACE="Swifty-PostgreSQL.xcworkspace"
    - OSX_APP_SCHEME="Swifty-PostgreSQL"
    - OSX_SDK=macosx10.12
    - FRAMEWORK_NAME="SwiftyPostgreSQL"
  matrix:
    - DESTINATION="arch=x86_64"                      SCHEME="$OSX_APP_SCHEME"           SDK="$OSX_SDK"     RUN_TESTS="NO"    BUILD_EXAMPLE="YES"

before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
before_deploy:
  - carthage build --no-skip-current
  - carthage archive $FRAMEWORK_NAME
